export const CAMERA_MODES = ['chase', 'bonnet', 'driver', 'dickey', 'overview'] as const;

export type CameraMode = (typeof CAMERA_MODES)[number];
export type ActiveCameraMode = CameraMode | 'reverse';

export const SIMULATOR_CONFIG = {
  world: {
    background: '#92c7f4',
    fogColor: '#92c7f4',
    fogNear: 65,
    fogFar: 320,
  },
  vehicle: {
    acceleration: 19,
    aerodynamicDrag: 0.016,
    bodyLean: 0.18,
    brakeStrength: 34,
    maxForwardSpeed: 40,
    maxReverseSpeed: 12,
    collisionProbeHeight: 0.9,
    collisionProbeLength: 1.5,
    collisionRadius: 1.05,
    modelYawOffset: 0,
    orientationLerp: 9,
    reverseAcceleration: 10,
    rideHeight: 0.62,
    rollingResistance: 2.4,
    steerResponse: 11,
    trackWidth: 1.72,
    turnGrip: 0.052,
    visualFootprint: 4.65,
    wheelBase: 2.8,
    maxSteerAngle: 0.88,
    boostMultiplier: 1.22,
  },
  camera: {
    chase: {
      accelerationPositionOffset: [0, 0.12, -0.85] as const,
      baseFov: 56,
      followDamping: 7.2,
      localLookOffset: [0, 1.05, 4.9] as const,
      localPositionOffset: [0, 2.45, -6.6] as const,
      speedPositionOffset: [0, 0.45, -3.2] as const,
    },
    bonnet: {
      accelerationPositionOffset: [0, 0, 0] as const,
      baseFov: 68,
      followDamping: 11,
      localLookOffset: [0, 1.02, 14] as const,
      localPositionOffset: [0, 1.08, 2.02] as const,
      speedPositionOffset: [0, 0, 0] as const,
    },
    driver: {
      accelerationPositionOffset: [0, 0, 0] as const,
      baseFov: 74,
      followDamping: 11,
      localLookOffset: [0.18, 1.14, 14] as const,
      localPositionOffset: [0.18, 1.12, 0.22] as const,
      speedPositionOffset: [0, 0, 0] as const,
    },
    dickey: {
      accelerationPositionOffset: [0, 0.18, -1.8] as const,
      baseFov: 64,
      followDamping: 8,
      localLookOffset: [0, 1.1, 10] as const,
      localPositionOffset: [0, 1.72, -3.9] as const,
      speedPositionOffset: [0, 0.26, -3.1] as const,
    },
    overview: {
      accelerationPositionOffset: [0, 0, 0] as const,
      baseFov: 52,
      followDamping: 4.5,
      localLookOffset: [0, 0.8, 4] as const,
      localPositionOffset: [0, 17, -15] as const,
      speedPositionOffset: [0, 0, 0] as const,
    },
    reverse: {
      accelerationPositionOffset: [0, 0, 0] as const,
      baseFov: 58,
      followDamping: 6.2,
      localLookOffset: [0, 1.05, -2.8] as const,
      localPositionOffset: [0, 2.15, 6.4] as const,
      speedPositionOffset: [0, 0, 0] as const,
    },
  },
} as const;
